apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagementservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermanagementservice
  template:
    metadata:
      labels:
        app: usermanagementservice
    spec:
      serviceAccountName: resource-access
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: usermanagementservice
          image: ghcr.io/vivrish/usermanagementservice:latest
          ports:
            - containerPort: 8060
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "cloud"
            - name: INSTANCE_CONNECTION_NAME
              value: "xent-436317:europe-central2:main-postgres"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/secrets/credentials.json"
          volumeMounts:
            - name: cloud-sql-instance-credentials
              mountPath: /secrets
              readOnly: true

          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
          command:
            [
              "/cloud_sql_proxy",
              "-instances=$(INSTANCE_CONNECTION_NAME)=tcp:5432",
              "-credential_file=/secrets/credentials.json",
            ]
          volumeMounts:
            - name: cloud-sql-instance-credentials
              mountPath: /secrets
              readOnly: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: cloud-sql-instance-credentials
          secret:
            secretName: cloud-sql-credentials
