apiVersion: v1
kind: Service
metadata:
  name: usermanagementservice
spec:
  type: ClusterIP
  selector:
    app: usermanagementservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8060
