apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: apigateway
          image: ghcr.io/vivrish/apigateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
