apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: eureka
          image: ghcr.io/vivrish/eureka:latest
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
