apiVersion: apps/v1
kind: Deployment
metadata:
  name: chats-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chats-db
  template:
    metadata:
      labels:
        app: chats-db
    spec:
      containers:
        - name: chats-db
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: chats_database
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
