apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chatservice
  template:
    metadata:
      labels:
        app: chatservice
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: chatservice
          image: ghcr.io/vivrish/chatservice:latest
          ports:
            - containerPort: 8100
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
