apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatservice
  template:
    metadata:
      labels:
        app: chatservice
    spec:
      serviceAccountName: resource-access
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: chatservice
          image: ghcr.io/vivrish/chatservice:latest
          ports:
            - containerPort: 8100
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "cloud"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
