apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: ClusterIP
  ports:
    - name: outside
      port: 9092
      targetPort: 9092
    - name: inside
      port: 9093
      targetPort: 9093
  selector:
    app: kafka
